### ISSUE TITLE
Stream prematurely closed on the 999th request

### ISSUE THREAD

**Issue by pranaygp** [grantila/fetch-h2#2]
Something I've noticed is, after making *exactly* 998 requests without closing a connection, the 999th request will always fail with a "Stream prematurely closed" error:

stack trace:
```
Error: Stream prematurely closed
    at stream.on.errorCode (/Users/pranaygp/github/now-cli/node_modules/fetch-h2/dist/lib/fetch.js:117:32)
    at ClientHttp2Stream.<anonymous> (/Users/pranaygp/github/now-cli/node_modules/callguard/dist/index.js:41:30)
    at emitOne (events.js:120:20)
    at ClientHttp2Stream.emit (events.js:210:7)
    at emit (internal/http2/core.js:139:8)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

likely some issue with node's `http2`?

**Comment by pranaygp** [comment]
Not able to reproduce this with a test case:

FYI, I added this test case:

```
	it( 'should be able to make 999 subsequent POST requests without an issue', async ( ) => 
	{
		const { server, port } = await makeServer( );

		let requestsLeft = 1000;

		async function makeRequest() {
			console.log('requestsLeft: %d', requestsLeft);
			if(requestsLeft <= 0) {
				return await server.shutdown( );
			}
			requestsLeft--;

			const stream = through2( );
			
			stream.write( "foo" );
	
			const eventual_response = fetch(
				`http://localhost:${port}/echo`,
				{
					method: 'POST',
					body: new StreamBody( stream ),
					headers: { 'content-length': '6' },
				}
			);
	
			await delay( 1 );
	
			stream.write( "bar" );
			stream.end( );

			const response = ensureStatusSuccess( await eventual_response );
			
			const data = await response.text( );
			expect( data ).to.equal( "foobar" );

			return await makeRequest()
		}

		return await makeRequest();
	} );
```

and it passed...

Still trying to see if I can repro the issue outside of my use contenxt

**Comment by grantila** [comment]
"Stream prematurely closed" is an error I throw when the stream gets a [`streamClosed`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_streamclosed) *before* it either completed or failed (only if the error code is `NGHTTP2_NO_ERROR` meaning it didn't really fail).
I've seen this occur in other occasions, so it's a bit sporadic unfortunately. This could also be the cause or not sending enough data, probably when 'content-length' is set, but not enough bytes are sent before the stream is ended, so make sure this is not the case for you.
Also, since in Node.js 8.8 you can't stream more than 16kb data, so e.g. it will fail if you send more than 1000 chunks of 16 bytes each (this is being fixed), it could be related.

**Comment by pranaygp** [comment]
Turns out this wasn't actually an issue with `fetch-h2`, but `nginx` on our backend.

http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests

completely missed this configuration option 😆

**Comment by pranaygp** [comment]
@grantila 

Given that issue, do you think it makes sense to implement an optional configuration argument that lets you define max requests per connection? If a connection hits the max request, it will create a new connection, re-route future requests to the new connection, and then when all ongoing requests on the old connection return, we destroy the old connection.

**Comment by grantila** [comment]
That does sound application specific and is against the philosophy regarding H2's *1 socket (session) per origin*.
You could wrap around `fetch-h2`'s *contexts* and create a context, fetch *n* requests and then create a new context. Since it's all promise based, you could relatively easily *await* all connections in a context and then manually `disconnect` it when all have resolved.
But it doesn't fit this module I think, there's nothing in H2 that deals with this afaik.

**Comment by pranaygp** [comment]
Yup! That ended up being how I implemented it. Glad you exposed the concept
of contexts with fetch-h2.

It makes sense that this should be userland given the philosophy of
fetch-h2. I hope anyone debugging a similar, easy to miss issue, finds this
:)
