### ISSUE TITLE
Improve perf with JSONStream

### ISSUE THREAD

**Issue by pranaygp** [grantila/fetch-h2#3]
When the response from a server is a stream, I wonder if using [JSONStream](https://github.com/dominictarr/JSONStream) to return JSON objects would make things better instead of waiting for the entire response before parsing from JSON (as is the current case with `res.json()`

I think this would be equivalent to a user just doing:

```
res.readable().pipe(JSONStream.parse(...))
```

Just wondering if you have any thoughts about this being userland vs having it be a part of `fetch-h2`?

**Comment by grantila** [comment]
I'd say, what you just wrote is the precise way to solve it, and in userland. Some people want to stream JSON, others will stream huge files, some might stream into transcoders and whatnot.
You're right that one should only use `.json()` when it's a small response, and I'm thinking of adding a maximum response body size limit (per request) so that one can *assure* `.json()` not to consume too much memory.

JSONStream particularly is relatively complex, with lots of configurability. This is something you certainly want to control manually, and
`(await res.readable()).pipe(JSONStream.parse(...))`
is surely the right and tight way to go. Don't forget the `await` ;)
