### ISSUE TITLE
is parseInt necessary on http2 status?

### ISSUE THREAD

**Issue by c0b** [grantila/fetch-h2#7]
I've played the http2 module of nodejs version 8 for a while, on `'response'` event callback, the `headers[':status']` is already an integer, like 200, 302, see the following example; wonder why does your code need to convert it to string then do parseInt? also, the javascript object support index an object by a integer, it implicitly convert the index to string, why do you need to convert the integer status to string? is just for explicit?

https://github.com/grantila/fetch-h2/blob/master/lib/fetch.ts#L288-L293

![image](https://user-images.githubusercontent.com/14798161/32358684-71decf86-c01e-11e7-8781-9242477f709d.png)

```js
[ { ':status': 200,
    expires: 'Fri, 03 Nov 2017 02:05:07 GMT',
    date: 'Fri, 03 Nov 2017 02:05:07 GMT',
    'cache-control': 'private, max-age=0, must-revalidate, no-transform',
    etag: '"cX5UmbB_R-S07ii743IKGH9YCYM/MTUwNjcyNDE0MDQwMg"',
    vary: 'Origin, X-Origin',
    'content-type': 'application/json; charset=UTF-8',
    'content-encoding': 'gzip',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '1; mode=block',
    'content-length': '409',
    server: 'GSE',
    'alt-svc': 'quic=":443"; ma=2592000; v="41,39,38,37,35"' },

> var isRedirectStatus = { '302': true }
undefined
> isRedirectStatus[302]
true
> isRedirectStatus[200]
undefined
```

**Comment by grantila** [comment]
Interesting, @c0b... Yes, explicitness for indexing. Might be unnecessary, but if it's done by the VM, I can just as well do it.

Regarding the status, that's actually not a real header, but a pseudo header. I guess that's why it's a number. This goes against the [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_headers_object) though, which states; *"Property values should be strings (if they are not they will be coerced to strings) or an Array of strings (in order to send more than one value per header field)."*.
The `'' + x` is to cast the (potential) array to a string, and makes TypeScript happy. It wasn't meant to cast a number to a string, although that's what happens here.

I'm uncomfortable *expecting* it to continue to be a number, although that's what Node.js currently gives you. The docs say otherwise, so I'll rather continue to be explicit, for future safety.

**Comment by c0b** [comment]
if you read http2 rfc (and https://hpbn.co/http2/) those headers are compressed in HPACK and a few are pseudo headers: the `:method` `:schema` `:authority` `:path`, and `:status` on response; pseudo headers are always present and once only, header names are not sent, only the values; the values are in their original form `:status` is sent as integer, and no duplicate; and http2 does not have statusText.

in that case, I would like to file an issue to the documentation you linked and fix there.

**Comment by grantila** [comment]
Right. I did simplify the logic you pointed out though, so there's no unnecessary parseInt.
