### ISSUE TITLE
Translate Host -> :authority

### ISSUE THREAD

**Issue by pranaygp** [grantila/fetch-h2#9]
[curl does this](https://github.com/curl/curl/blob/544bfdebea2a9e8be1c01fc7954cd49638fe2803/lib/http2.c#L1888-L1892) thing where, when you use http2, it'll translate the Host header to the :authority pseudo-header.

Is that something `fetch-h2` should be doing too before making a request?

**Comment by matheuss** [comment]
I was investigating this later and tried to set my own `:authority`, but it's [not allowed](https://github.com/grantila/fetch-h2/blob/master/lib/headers.ts#L84) 🤔 I suppose it's a bug since the spec allows it?

**Comment by pranaygp** [comment]
Has to do with this line I think:
https://github.com/grantila/fetch-h2/blob/80ec896f88b58ae23263572ea161c0b22eb0ab3d/lib/headers.ts#L84-L86

**Comment by grantila** [comment]
Yeah, the [spec](https://tools.ietf.org/html/rfc2822#section-2.2) doesn't allow any pseudo-headers.

> A field name MUST be composed of printable US-ASCII characters (i.e., characters that have values between 33 and 126, inclusive), **except colon**.

This is probably why they chose to use colon for psuedo-headers, simply because they aren't legal *real headers*.

Converting `Host` to `:authority` does seem reasonable. @pranaygp did curl *convert* it or *copy* it to `:authority`, i.e. did it remove `host` as header, or have both of them?

**Comment by pranaygp** [comment]
It's definitely replacing it @grantila 
based on this fragment in `curl`

https://github.com/curl/curl/blob/544bfdebea2a9e8be1c01fc7954cd49638fe2803/lib/http2.c#L1888-L1896

**Comment by grantila** [comment]
Great digging, Sherlock.

**Comment by grantila** [comment]
Released in 0.0.12
